# Dataset and Training configuration
metadata_csv: "datasets/dummy_exp2/metadata.csv"
data_dir: "datasets/dummy_exp2/"
test_size: 0.2
random_seed: 42

# EEG Signal/Model Parameters
num_classes: 4
in_channels: 22
input_time: 1875

# Meta-dataset Parameters
k_shot: 1
q_query: 1

# Training configuration
epochs: 100
num_tasks_train: 10
num_tasks_test: 5
inner_steps: 1
inner_lr: 0.01
meta_lr: 0.001

# Model save/load
save_model: checkpoints/maml_eeg.pth
load_model: checkpoints/maml_eeg.pth  # only used in test mode