# Dataset and Training Configuration
metadata_csv: "datasets/dummy_exp2/metadata.csv"
data_dir: "datasets/dummy_exp2/"
test_size: 0.2
random_seed: 42

# EEG Signal Parameters
in_channels: 22
input_time: 1875
num_classes: 4

# Model Parameters
embedding_dim: 128
kernel_size: 2
dilation : 1

# Meta-dataset Parameters
num_tasks_train: 10
num_tasks_test: 5
k_shot: 1
q_query: 1

# Training configuration
epochs: 100
learning_rate: 0.001

# Model save/load
save_model: checkpoints/snail_eeg.pth
load_model: checkpoints/snail_eeg.pth  # only used in test mode